### ISSUE TITLE
部署后预览路径访问不到。

### ISSUE THREAD

**Issue by MhandsomeM** [phynos/WebTopo#8]
http://localhost:4000/WebTopo/fullscreen。
fullscreen路径访问不到，404.
请问是哪个步骤可能出错了？

**Comment by phynos** [comment]
因为使用了history模式，必须使用nginx进行URL重写，类似下面这样：
        location /WebTopo/dist/spa {
            index  /WebTopo/dist/spa/index.html; 
            if (!-e $request_filename) {
                rewrite ^/(.*) /WebTopo/dist/spa/index.html last;
                break;
            }
        }
